// The API url and the city we want to check...
var url = "http://api.openweathermap.org/data/2.5/weather?callback=?";

var countries = [
"Abkhazia",
"Afghanistan",
"Aland Islands",
"Albania",
"Algeria",
"American Samoa",
"Andorra",
"Angola",
"Anguilla",
"Antarctica",
"Antigua and Barbuda",
"Argentina",
"Armenia",
"Aruba",
"Ascension",
"Australia",
"Austria",
"Azerbaijan",
"Bahamas",
"Bahrain",
"Bangladesh",
"Barbados",
"Belarus",
"Belgium",
"Belize",
"Benin",
"Bermuda",
"Bhutan",
"Bolivia",
"Bonaire",
"Bosnia and Herzegovina",
"Botswana",
"Brazil",
"British Virgin Islands",
"Brunei",
"Bulgaria",
"Burkina Faso",
"Burundi",
"Cambodia",
"Cameroon",
"Canada",
"Cape Verde",
"Central African Republic",
"Cayman Islands",
"Chad",
"Chile",
"China",
"Cocos (Keeling) Islands",
"Colombia",
"Comoros",
"Cook Islands",
"Costa Rica",
"Christmas Island",
"Croatia",
"Cuba",
"Cyprus",
"Czech Republic",
"Denmark",
"Djibouti",
"Dominica",
"Dominican Republic",
"Donetsk`s Republic",
"DR Congo",
"East Timor",
"Ecuador",
"Egypt",
"El Salvador",
"Equatorial Guinea",
"Eritrea",
"Estonia",
"Ethiopia",
"Falkland Islands",
"Faroe Islands",
"Fiji",
"Finland",
"France",
"FS Micronesia",
"French Guiana",
"French Polynesia",
"Gabon",
"Gambia",
"Georgia",
"Germany",
"Ghana",
"Gibraltar",
"Greece",
"Greenland",
"Grenada",
"Guam",
"Guadalupe",
"Guatemala",
"Guernsey",
"Guinea",
"Guinea-Bissau",
"Guyana",
"Haiti",
"Honduras",
"Hong Kong",
"Hungary",
"Iceland",
"India",
"Indonesia",
"Iran",
"Iraq",
"Ireland",
"Isle of Man",
"Israel",
"Italy",
"Ivory Coast",
"Jamaica",
"Jan Mayen",
"Japan",
"Jersey",
"Jordan",
"Kazakhstan",
"Kenya",
"Kiribati",
"Kosovo",
"Kuwait",
"Kyrgyzstan",
"Laos",
"Latvia",
"Lebanon",
"Lesotho",
"Liberia",
"Libya",
"Liechtenstein",
"Lithuania",
"Luhansk Republic",
"Luxembourg",
"Macau",
"Macedonia",
"Madagascar",
"Malawi",
"Malaysia",
"Maldives",
"Mali",
"Malta",
"Marshall Islands",
"Martinique",
"Mauritania",
"Mauritius",
"Mayotte",
"Mexico",
"Moldova",
"Monaco",
"Mongolia",
"Montserrat",
"Montenegro",
"Morocco",
"Mozambique",
"Myanmar",
"Nagorno-Karabakh",
"Namibia",
"Nauru",
"Nepal",
"Netherlands",
"Netherlands Antilles",
"New Zealand",
"Nicaragua",
"Niger",
"Nigeria",
"Niue",
"Norfolk Island",
"North Korea",
"Northern Cyprus",
"Northern Mariana Islands",
"Norway",
"Oman",
"Pakistan",
"Palau",
"Panama",
"Papua New Guinea",
"Paraguay",
"Peru",
"Philippines",
"Pitcairn Islands",
"Poland",
"Portugal",
"Puerto Rico",
"Qatar",
"Romania",
"Russia",
"Rwanda",
"Republic of the Congo",
"Saba",
"Sahrawi Republic",
"Saint Barthelemy",
"Saint Helena",
"Saint Kitts and Nevis",
"Saint Lucia",
"Saint Martin",
"Saint Pierre and Miquelon",
"Saint Vincent and the Grenadines",
"Samoa",
"San Marino",
"Sao Tome and Principe",
"Saudi Arabia",
"Sealand",
"Senegal",
"Serbia",
"Seychelles",
"Sierra Leone",
"Singapore",
"Sint Eustatius",
"Sint Maarten",
"Slovakia",
"Slovenia",
"Solomon Islands",
"Somalia",
"Somaliland",
"South Africa",
"South Georgia and the South Sandwich Islands",
"South Korea",
"South Ossetia",
"South Sudan",
"Spain",
"Sri Lanka",
"Sudan",
"Suriname",
"Svalbard",
"Swaziland",
"Sweden",
"Switzerland",
"Syria",
"T[edit]",
"Taiwan",
"Tajikistan",
"Tanzania",
"Thailand",
"Timor-Leste",
"Togo",
"Tokelau",
"Tonga",
"Transnistria",
"Tibet",
"Trinidad and Tobago",
"Tristan da Cunha",
"Tunisia",
"Turkey",
"Turkmenistan",
"Turks and Caicos",
"Tuvalu",
"U[edit]",
"Uganda",
"Ukraine",
"United Arab Emirates",
"United Kingdom",
"United States of America",
"Uruguay",
"US Virgin Islands",
"Uzbekistan",
"V[edit]",
"Vanuatu",
"Venezuela",
"Vietnam",
"W[edit]",
"Wallis and Futuna",
"Western Sahara",
"Y[edit]",
"Yemen",
"Z[edit]",
"Zambia",
"Zimbabwe"
]







function doWeatherSearch() {

	var q = document.getElementById('search').value;
	//var q = $('#search').val()

	// Change the data to be dynamic
	var data = {
		'q':q,
		'units':'metric',
		'APPID':"6dec5fb891e6e243c9d8c20351998e67"
	}

	// Go call the URL and pass 2 parameters (q=city, units=metric/imperial)
	$.getJSON(url, data, function(result)
	{

		// If no result??
		console.log("HERE!!!")

		// callback (runs when the data comes back)
		// Update your interface
		console.log(result);
		console.log(result.main.temp);

		document.getElementById('temp').innerHTML = Math.round(result.main.temp) + "&deg;C";
		document.getElementById('city').textContent = result.name;
		// Update the interface to reflect the information that's returned

		if (result.main.temp > 10) {
			document.querySelector('body').style.backgroundColor = 'rgb(228, 194, 185)'
		}
		else {
			document.querySelector('body').style.backgroundColor = 'rgb(160, 198, 210)'
		}


	});

}

document.getElementById('go').addEventListener('click', doWeatherSearch)






addEventListener('keyup', function() {
	var q = document.getElementById('search').value;

	console.log(q);

})
